#!/usr/bin/env python3

import sys

contents = open(sys.argv[1], 'rb').read()
hiout = open(sys.argv[2], 'wb')
loout = open(sys.argv[3], 'wb')

romsize = 2 * 128 * 1024

if len(contents) > romsize:
    print("Too big!")
    sys.exit(1)

# pad to 256KB
contents += bytes([255] * (romsize - len(contents)))

# divide into two separate low/high ROMs
while contents:
    hiout.write(bytes([contents[1], contents[0]]))
    loout.write(bytes([contents[3], contents[2]]))
    contents = contents[4:]
